services:
  postgres:
    image: postgres:16-alpine
    container_name: zagotours-db
    restart: always
    environment:
      POSTGRES_USER: zagotours
      POSTGRES_PASSWORD: zagotours123
      POSTGRES_DB: zagotours_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
